### ISSUE TITLE
1.0 release checklist

### ISSUE THREAD

**Issue by BastiHz** [BastiHz/fractalplotr#13]
- [ ] Bump version number.
- [ ] Write in the NEWS
- [ ] Make a dev branch for further development
